# Generated by Django 5.2.1 on 2025-05-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='url',
            field=models.URLField(help_text='Apunta al Home.html o alguna página'),
        ),
    ]
