# Generated by Django 5.2.1 on 2025-05-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_genero_remove_libro_calificacion_remove_libro_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='url',
        ),
        migrations.AddField(
            model_name='libro',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
