# Generated by Django 5.2.1 on 2025-05-28 13:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_remove_libro_url_libro_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autores_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genero',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libro',
            name='archivo',
            field=models.FileField(help_text='Solo archivos EPUB', upload_to='libros/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['epub'])]),
        ),
    ]
